from datetime import datetime, timezone
from typing import Dict, Any, Optional
import uuid
from pydantic import BaseModel, Field, ConfigDict


class Alert(BaseModel):
    """
    Structured threat alert generated by PassiveGuard AI.
    
    STRICT PASSIVE CONSTRAINT:
    Alerts represent security findings for SOC operator awareness.
    They NEVER trigger automated active network mitigations, packet drops, or active probes.
    """
    alert_id: str = Field(default_factory=lambda: f"ALT-{uuid.uuid4().hex[:8].upper()}", description="Unique alert ID")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Alert generation timestamp")
    flow_id: str = Field(..., description="Flow identifier associated with this alert")
    source_ip: str = Field(..., description="Observed source IP address")
    destination_ip: str = Field(..., description="Observed destination IP address")
    source_port: int = Field(..., ge=0, le=65535, description="Observed source port")
    destination_port: int = Field(..., ge=0, le=65535, description="Observed destination port")
    protocol: str = Field(..., description="Transport layer protocol")
    threat_class: str = Field(..., description="Classification of threat (DDoS, C2_Beaconing, DGA, etc.)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Normalized risk / confidence score")
    severity: str = Field(..., description="Alert severity: INFO, LOW, MEDIUM, HIGH, CRITICAL")
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Supporting telemetry evidence and metrics")
    detector_name: str = Field(..., description="Name of primary detector or risk engine creating alert")
    model_version: str = Field(default="v0.1.0-scaffold", description="Model version tag")
    source: str = Field(default="controlled_demo", description="Source metadata tagging (e.g. controlled_demo, live_pcap)")

    model_config = ConfigDict(frozen=True)
